image: docker:stable

variables:
  DOCKER_DRIVER: overlay2
  DOCKER_IMAGE: "itdogsoftware/php-fpm"

services:
  - docker:dind

stages:
  - build
  - push

variables:

build-test:
  stage: build
  image: docker:latest
  services:
    - docker:dind
  script:
     - echo ${CI_COMMIT_SHORT_SHA}
#    - docker build --tag ${DOCKER_IMAGE}:${CI_COMMIT_SHORT_SHA} --tag ${DOCKER_IMAGE}:latest .
  when: manual

release:
  stage: push
  image: docker:latest
  services:
    - docker:dind
  before_script:
    - docker login -u "$DOCKERHUB_USERNAME" -p "$DOCKERHUB_TOKEN"
  script:
    - docker build -t $DOCKER_IMAGE:${CI_COMMIT_TAG} .
    - docker tag $DOCKER_IMAGE:${CI_COMMIT_TAG} $DOCKER_IMAGE:latest
    - docker push $DOCKER_IMAGE:${CI_COMMIT_TAG}
    - docker push $DOCKER_IMAGE:latest
  when: manual
  only:
    - master
    - tags
