image: docker:stable

variables:
  DOCKER_DRIVER: overlay2

services:
  - docker:dind

stages:
  - build
  - push

variables:

build-test:
  stage: build
  image: docker:latest
  services:
    - docker:dind
  script:
    - docker build --tag itdogsoftware/php-fpm:${CI_COMMIT_SHORT_SHA} .
  when: manual

release:
  stage: push
  image: docker:latest
  services:
    - docker:dind
  before_script:
    - docker login -u "$DOCKERHUB_USERNAME" -p "$DOCKERHUB_TOKEN"
  script:
    - docker build --tag itdogsoftware/php-fpm:${CI_COMMIT_TAG} --tag itdogsoftware/php-fpm:latest .
    - docker push itdogsoftware/php-fpm:${CI_COMMIT_TAG}
    - docker push itdogsoftware/php-fpm:latest
  when: manual
  only:
    - master
    - tags
